name: Update Personal Website Screenshot

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name for the PR"
        required: false
        default: "update-personal-website-screenshot"

jobs:
  update-screenshot:
    name: Update Personal Website Screenshot
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Install system dependencies
        run: npx playwright install-deps chromium

      - name: Update personal website screenshot
        run: npm run screenshot:update-personal-website

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update personal website screenshot"
          title: "📸 Update Personal Website Screenshot"
          body: |
            ## 📸 Personal Website Screenshot Update

            This PR updates the screenshot for the personal website project on the projects page.

            ### Changes
            - Updated `personal-website.png` with current live site appearance
            - Modified projects page to use the new screenshot
            - Generated from live zaahir.ca site

            ### Review Instructions
            1. Check that the new screenshot looks good and matches the current site design
            2. Verify the projects page displays the screenshot correctly
            3. Ensure image dimensions are consistent with other project screenshots

            _This PR was automatically created by the Update Screenshot workflow._
          branch: ${{ github.event.inputs.branch_name || 'update-personal-website-screenshot' }}
          delete-branch: true
          labels: |
            enhancement
            automated
            screenshot
